export const TYPES = {
	Application: Symbol.for('Application'),
	UserController: Symbol.for('UserController'),
	AuthController: Symbol.for('AuthController'),
	AuthService: Symbol.for('AuthService'),
	LoggerService: Symbol.for('LoggerService'),
	UserService: Symbol.for('UserService'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UserRepository: Symbol.for('UserRepository'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	PostController: Symbol.for('PostController'),
	PostRepository: Symbol.for('PostRepository'),
	PostService: Symbol.for('PostService'),
	AuthMiddleware: Symbol.for('AuthMiddleware'),
	FilesService: Symbol.for('FilesService'),
	PhotosController: Symbol.for('PhotosController'),
	PhotosService: Symbol.for('PhotosService'),
	PhotosRepository: Symbol.for('PhotosRepository'),
	PlaylistController: Symbol.for('PlaylistController'),
	PlaylistService: Symbol.for('PlaylistService'),
	PlaylistRepository: Symbol.for('PlaylistRepository'),
	AudiosController: Symbol.for('AudiosController'),
	AudiosService: Symbol.for('AudiosService'),
	AudiosRepository: Symbol.for('AudiosRepository'),
};
